### PR TITLE
Removing GMs, PREVIEW versions

### PR DESCRIPTION
**Pull request by rbukovansky**
@kylef Merge if you will

As suggested in #10

I personally would leave there just versions:
2.2.1
3.0
3.0.1
3.0.2

When 3.1 is released then just these:
2.2.1
3.0.2 (or higher of 3.0.x if released)
3.1.anything

But that's up to you...

### CODE REVIEW

**Comment by kylef** [comment]
I don't think we want to do this as it will break all historical builds. For example, if I pull down some older code that uses one of these releases then when I try installing the swift I will get an error.

**Comment by rbukovansky** [comment]
@kylef Well... I'm fine leaving previews there... But those SNAPSHOTS should go...

BTW How about some fallback version? Let's say, from now on swiftenv will fallback to 3.0 if any version is not found...

**Comment by kylef** [comment]
@rbukovansky Why should they go?

**Comment by rbukovansky** [comment]
1. Does anybody cares about them?
2. Are they still available for download?

**Comment by rbukovansky** [comment]
@kylef But if you are not OK with this PRs, that's fine, no biggie... Just an idea... So, just close them... OK?

**Pull request closed without merging**
